---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
          include_paths:
            - "app/components/**/*.ts"

  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
exclude_paths:
- js/underscore.js
- js/mousetrap.js
