---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    channel: cronopio
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "*"
exclude_paths:
- js/underscore.js
- js/mousetrap.js
